#!/bin/bash

log_folder=/tmp/log
run_folder=/tmp/run

if [[ ! -d $log_folder ]]; then
    mkdir "$log_folder"
fi

if [[ ! -d $run_folder ]]; then
    mkdir "$run_folder"
fi

./tcollector.py --logfile "$log_folder/tcollector.log" -P "$run_folder/tcollector.pid" --dedup-interval 0 "$@"

